name: PR 微信通知
on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  wechat-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to WeChat
        uses: chacha1123/github-serverchan-action@master
        with:
          key: SCT329960TAEAv4JU183TkNggN2jQyZGC2
          title: GitHub 有新的 PR
          desp: |
            仓库：${{ github.repository }}
            标题：${{ github.event.pull_request.title }}
            发起人：${{ github.actor }}
            状态：${{ github.event.action }}
            链接：${{ github.event.pull_request.html_url }}
